### ISSUE TITLE
module 'textacy.vsm' has no attribute 'doc_term_matrix'

### ISSUE THREAD

**Issue by evangelionys** [usnistgov/nestor-tmp2#1]
![image](https://user-images.githubusercontent.com/22282867/31614798-9584dc4a-b255-11e7-915d-ea27e4234f28.png)

**Comment by rtbs-dev** [comment]
Good catch, it looks like the the textacy package has deprecated usage of the textacy.vsm.doc_term_matrix() function ([see here](https://github.com/chartbeat-labs/textacy/releases/tag/0.4.0)).

**Comment by rtbs-dev** [comment]
Based on the updated docs on the textacy main-page, everything looks like it's following a scikit-learn style interface now (hallelujah!) This is fantastic for some of the analysis we need to do, but is breaking the tf-idf loop as it's currently written. 

I think at some point we need to decide if we will keep basing thinks on Textacy or start writing custom spaCy pipelines now that the new  [extension API](https://explosion.ai/blog/spacy-v2-pipelines-extensions) is out. Or maybe some hybrid of those two.

**Comment by evangelionys** [comment]
That sounds really interesting. Can you tell me which version of textacy were you using? Maybe I can use the previous version and try the code on my computer.

**Comment by rtbs-dev** [comment]
I'm on 0.3.4, built on spacy 1.8.2 in python 3.6

**Comment by rtbs-dev** [comment]
@evangelionys  another new commit, I've made a "band-aid" to get everything working with Textacy 0.4.1. Versions are now printed in the tutorial.ipynb heading. 

Please verify it works now, and I'll close this. Thanks!

**Comment by evangelionys** [comment]
It fixed the problem! That's amazing. Thanks!

**Comment by rxng** [comment]
@tbsexton was there an fix for this? I am still getting this error

doc_term_matrix, id2term = textacy.vsm.doc_term_matrix(terms_lists, weighting='tfidf',smooth_idf=True, min_df=0.05, max_df=.99, max_n_terms=100000)
AttributeError: 'module' object has no attribute 'doc_term_matrix'

have tried import textacy.vsm

but to no avail as well.

**Comment by rtbs-dev** [comment]
@rxng is this for the Nestor package? This is the nestor repo, which used textacy as a dependency back in v0.2...you might need to go to the textacy repo for help with using that package.

**Comment by rohetoric** [comment]
If we write direct import statements like - 
`import textacy.vsm
import textacy.tm`

instead of
 
`import textacy`

we won't get errors like `textacy has no attribute as vsm` etc. This worked for me. 
I hope I make sense here.
